# Generated by Django 4.0.3 on 2022-03-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nat_id', models.CharField(max_length=11)),
                ('birth_date', models.CharField(max_length=12)),
                ('seri_no', models.CharField(max_length=20)),
            ],
        ),
    ]
