# Generated by Django 4.0.3 on 2022-03-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lion', '0002_person_created_date_alter_person_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='İsim Soyisim'),
        ),
    ]
